
public enum Sigla {
    PMDB, PTB, PDT, PT, DEM, PCDOB, PSB, PSDB, PTC, PSC, 
    PMN, PRP, PPS, PV, AVANTE,PP,PSTU,PCB,PRTB,PHS,PSDC,PCO,PODE,
    PSL,PRB,PSOL,PR,PSD,PPL,PEN,PROS,SD,NOVO,REDE,PMB;

}
